-- MySQL Script generated by MySQL Workbench
-- Thu Dec 12 10:59:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cazadorDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cazadorDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cazadorDB` DEFAULT CHARACTER SET utf8 ;
USE `cazadorDB` ;

-- -----------------------------------------------------
-- Table `cazadorDB`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cazadorDB`.`Categorias` (
  `categoria_id` INT(11) NOT NULL,
  `nombre_categoria` VARCHAR(50) NOT NULL,
  `descipcion_categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cazadorDB`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cazadorDB`.`Clientes` (
  `cliente_id` INT(11) NOT NULL,
  `correo_cliente` VARCHAR(30) NOT NULL,
  `nombre_cliente` VARCHAR(50) NOT NULL,
  `celular_cliente` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cazadorDB`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cazadorDB`.`Usuarios` (
  `empleado_id` INT(11) NOT NULL,
  `nombre_empleado` VARCHAR(50) NOT NULL,
  `usuario_actor` VARCHAR(30) NOT NULL,
  `contraseña` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`empleado_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cazadorDB`.`CopiasSeguridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cazadorDB`.`CopiasSeguridad` (
  `copia_id` INT(11) NOT NULL,
  `descipcion_copia` VARCHAR(300) NOT NULL,
  `fecha_copia_seguiridad` DATETIME NOT NULL,
  `empleado_id` INT(11) NOT NULL,
  PRIMARY KEY (`copia_id`, `empleado_id`),
  INDEX `fk_CopiasSeguridad_Usuarios1_idx` (`empleado_id` ASC) VISIBLE,
  CONSTRAINT `fk_CopiasSeguridad_Usuarios1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `cazadorDB`.`Usuarios` (`empleado_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cazadorDB`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cazadorDB`.`Proveedor` (
  `proveedor_id` INT(11) NOT NULL,
  `nombre_proveedor` VARCHAR(50) NOT NULL,
  `correo_proveedor` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`proveedor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cazadorDB`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cazadorDB`.`Pedidos` (
  `pedidos_id` INT(11) NOT NULL,
  `producto_id` INT(10) NOT NULL,
  `cantidad_productos` INT(3) NOT NULL,
  `fecha_entrega` DATETIME NOT NULL,
  `proveedor_id` INT(11) NOT NULL,
  PRIMARY KEY (`pedidos_id`),
  INDEX `fk_Pedidos_Proveedor1_idx` (`proveedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Proveedor1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `cazadorDB`.`Proveedor` (`proveedor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cazadorDB`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cazadorDB`.`Productos` (
  `producto_id` INT(11) NOT NULL,
  `nombre_producto` VARCHAR(50) NOT NULL,
  `cantidad_producto` INT(3) NOT NULL,
  `precio_producto` DECIMAL(10,0) NOT NULL,
  `categoria_id` INT(11) NOT NULL,
  PRIMARY KEY (`producto_id`),
  INDEX `fk_Productos_Categorias_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Categorias`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `cazadorDB`.`Categorias` (`categoria_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cazadorDB`.`Productos_has_Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cazadorDB`.`Productos_has_Pedidos` (
  `producto_id` INT(11) NOT NULL,
  `pedidos_id` INT(11) NOT NULL,
  PRIMARY KEY (`producto_id`, `pedidos_id`),
  INDEX `fk_Productos_has_Pedidos_Pedidos1_idx` (`pedidos_id` ASC) VISIBLE,
  INDEX `fk_Productos_has_Pedidos_Productos1_idx` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_has_Pedidos_Pedidos1`
    FOREIGN KEY (`pedidos_id`)
    REFERENCES `cazadorDB`.`Pedidos` (`pedidos_id`),
  CONSTRAINT `fk_Productos_has_Pedidos_Productos1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `cazadorDB`.`Productos` (`producto_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cazadorDB`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cazadorDB`.`Ventas` (
  `venta_id` INT(11) NOT NULL,
  `monto_venta` DECIMAL(2,0) NOT NULL,
  `venta_cancelada` TINYINT(4) NOT NULL,
  `producto_id` VARCHAR(45) NOT NULL,
  `empleado_id` INT(11) NOT NULL,
  `cliente_id` INT(11) NOT NULL,
  PRIMARY KEY (`venta_id`, `empleado_id`),
  INDEX `fk_Ventas_Usuarios1_idx` (`empleado_id` ASC) VISIBLE,
  INDEX `fk_Ventas_Clientes1_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Clientes1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `cazadorDB`.`Clientes` (`cliente_id`),
  CONSTRAINT `fk_Ventas_Usuarios1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `cazadorDB`.`Usuarios` (`empleado_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cazadorDB`.`Productos_has_Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cazadorDB`.`Productos_has_Ventas` (
  `producto_id` INT(11) NOT NULL,
  `venta_id` INT(11) NOT NULL,
  PRIMARY KEY (`producto_id`, `venta_id`),
  INDEX `fk_Productos_has_Ventas_Ventas1_idx` (`venta_id` ASC) VISIBLE,
  INDEX `fk_Productos_has_Ventas_Productos1_idx` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_has_Ventas_Productos1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `cazadorDB`.`Productos` (`producto_id`),
  CONSTRAINT `fk_Productos_has_Ventas_Ventas1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `cazadorDB`.`Ventas` (`venta_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
